jobs:
    build:
        
    deploy:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Deploy
              run: |
                echo "Deploying to production"
                echo "Deployed!"